### ISSUE TITLE
Multiline widont

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-v2/toolkit#144]
By [changing the RegEx slightly](https://forum.getkirby.com/t/kirbytext-widont/3368/3?u=lukasbestle), the `widont` helper could be used to be applied to more than one paragraph at once. I don't know if that would break expected behavior (depending on how it is currently used by Kirby users), but it is a nice idea.

**Comment by PaulMorel** [comment]
As I posted on the Forums, I ended up with [this on RegExr](http://www.regexr.com/3crcl). RegExr uses Javascript and uses the `g` flag. IIRC `g` is implicit with preg_replace_callback() in PHP, so no need to add it.

Of course I haven't tested it yet, but I think the results could be promising.
