### ISSUE TITLE
Send HTML emails using the Email class

### ISSUE THREAD

**Issue by lukasbestle** [getkirby-v2/toolkit#150]
See [this topic](https://forum.getkirby.com/t/sending-html-emails-with-toolkit-mail/3566?u=lukasbestle).

**Comment by ljacobs-sml** [comment]
I stumbled across my own resolution to this problem in trying to solve this problem again.. I guess this is what they mean by something coming "full circle".. Looking for newer posts on the matter, I came across @lukasbestle post. I wonder if the older solution would implement easily into things by just adding a new option to the email function?

https://forum.getkirby.com/t/is-there-a-way-to-send-html-emails/504/2
