### ISSUE TITLE
Wrong URL when tunnelling localhost

### ISSUE THREAD

**Issue by pedroborges** [getkirby-v2/toolkit#157]
With [ngrok](https://ngrok.com) (there are other services alike) I can share a local port with a client using a URL it provides, for example:

```
http://b183e8fd.ngrok.io -> localhost:8000
```

Kirby uses only `localhost:8000` to generate all URLs, not `b183e8fd.ngrok.io`. I can get Kirby to use the right URL by changing [line 321](https://github.com/getkirby/toolkit/blob/master/lib/url.php#L321) of `lib/url.php`:

```
// from:
return static::scheme() . '://' . server::get('SERVER_NAME', server::get('SERVER_ADDR')) . r($port, ':' . $port);
```

```
// to
return static::scheme() . '://' . server::get('HTTP_HOST', server::get('SERVER_ADDR'));
```

Is this something that can be fixed without messing with another use cases I'm not aware of?

**Comment by jaceq** [comment]
Hi, I have same issue, this is true whenever kirby is behind some proxy and runs on non standard port (not 80 and 443)... There should be a config option disabling port in $url 
(it seems like a if or 2 to achieve that)

**Comment by Pascalmh** [comment]
@jaceq https://github.com/getkirby/kirby/issues/255 this seems to be a good workaround for now.
