### ISSUE TITLE
Page Url in the native language - 404 not found

### ISSUE THREAD

**Issue by ilyaskorik** [getkirby-v2/toolkit#226]
Folders with names in native language do not work in Кirby. For example, I created folder with name "blog/1212-копия-на-русском-35" and Kirby and Kirby Panel can not find this page.

I found that this is the problem with routing. This is made specifically by design. Or can I send a patch?

**Comment by lukasbestle** [comment]
Feel free to send a pull request, but please note that we still don't recommend using non-ASCII characters in URLs. It can lead to all sorts of issues, especially because of the different Unicode normalization forms.
